media:
  input: static/images
  output: /images

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: content/posts

    # Generates:
    # my-post.ca.md
    # my-post.en.md
    filename: "{primary}.{fields.language}.md"

    view:
      fields: [title, language, date, draft]
      primary: title
      sort: date
      order: desc

    fields:
      - name: language
        label: Language
        type: select
        required: true
        options:
          values:
            - label: Català
              value: ca

            - label: English
              value: en

      - name: title
        label: Title
        type: string
        required: true

      - name: date
        label: Date
        type: date
        required: true

      - name: draft
        label: Draft
        type: boolean
        default: false

      - name: description
        label: Description
        type: text

      - name: tags
        label: Tags
        type: string
        list: true

      # Useful for Hugo multilingual linking
      - name: translationKey
        label: Translation Key
        type: string

      - name: body
        label: Content
        type: rich-text