baseURL = 'https://www.bolt-the-bird.com/'
locale = 'en-us'
title = 'Bolt the bird!'

[module]
  [[module.imports]]
    path = "github.com/jordinebot/hugo-leyline"
  [[module.imports]]
    path = "github.com/jordinebot/hugo-mtg-shortcodes"

[params]
  description = "Bolts, birds, and other MTG-themed nonsense."

  [params.footer]
    tagline = "Bolts, birds, and other MTG-themed nonsense."

[taxonomies]
  tag = "tags"

[[menus.main]]
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menus.main]]
  name = "Tags"
  url = "/tags/"
  weight = 20

[[menus.footer]]
  name = "GitHub"
  url = "https://github.com/jordinebot"
  weight = 10
  [menus.footer.params]
    icon = "github"

[[menus.footer]]
  name = "RSS"
  url = "/index.xml"
  weight = 20
  [menus.footer.params]
    icon = "rss"
