baseURL = 'https://www.bolt-the-bird.com/'
locale = 'en-us'
title = 'Bolt the Bird'

[module]
  [[module.imports]]
    path = "github.com/jordinebot/hugo-manaforge"

[params]
  logo = "/images/logo.webp"
  logoWidth = "100px"
  accentColor = "#FB1105"

[taxonomies]
  tag = "tags"
